print("   ,  ")
print("  o  ")
print(" (((")
print("(((((")
print(" VVV ")
print("  V  ")
print("   ,  ")
print("  o  ")
print(" (((")
print("(((((")
print(" VVV ")
print("  V  ")
print("   ,  " "   ,  ")
print("  o  " "   o  ")
print(" (((" "   (((")
print("(((((" " (((((")
print(" VVV " "  VVV ")
print("  V  " "   V  ")